version: '3.3'

services:
  skeleton:
    image: kalisio/kapp:dev
    environment:
      - DB_URL=mongodb://mongodb:27017/kapp
    ports:
      - "8080:8081"
    networks:
      - skeleton
  mongodb:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - skeleton

volumes:
  mongodb:

networks:
  skeleton: